# use double quotes instead of single quotes
singleQuote: true

# use 2 spaces for indentation
tabWidth: 2

# add trailing commas
trailingComma: 'es5'

# add semi colons
semi: false

# wrap prose at 80 characters
printWidth: 80
