version: '3.8'

services:
  app:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./pamnani-time-service-account-secrets.json:/app/pamnani-time-service-account-secrets.json
    restart: always
